### ISSUE TITLE
Cannot edit names

### ISSUE THREAD

**Issue by UtilityHotbar** [rr-/pq-cli#14]
Currently running this on ubuntu WSL. When creating a new character, I cannot press backspace to change the name, only add more characters to the existing name.

**Comment by NoxMortem** [comment]
On windows ctrl+backspace worked.

**Comment by rr-** [comment]
You mean you can't edit the character name in the character creation
window, or you can't rename an existing character? In it's the first,
the problem is with the terminal emulator you're using, as for the
latter, I believe vanilla PQ doesn't allow you that either.

**Comment by UtilityHotbar** [comment]
@rr- I couldn't edit it in the character creation window, but control backspace has worked for me, thank you @NoxMortem !
