### ISSUE TITLE
Feature request: Command-line parameters to specify which character to run

### ISSUE THREAD

**Issue by MelGrubb** [rr-/pq-cli#15]
It would help my character's progress if he didn't have to wait for me to run the game every time the server restarts. I'd like to specify which file to run on the command line so that I can script the game to auto-launch on startup. If this can already be done, then perhaps only the documentation needs to be updated.

**Comment by rr-** [comment]
@MelGrubb please see if https://github.com/rr-/pq-cli/pull/16 works for you. Thanks

**Comment by MelGrubb** [comment]
I’m afraid I am in no way set up to build and run Python. I could get there, but not in any kind of short timeframe. I didn’t expect this fast of a response, actually. I figured this would sit in the backlog for a while before getting picked up. Thank you for looking at it. I’ll likely have to wait a while before I can get set up to evaluate the PR myself, or I’ll just have to wait for it to become official and test the result that way.

**Comment by rr-** [comment]
Hmm you can just `git clone` this repository, `git checkout origin/cli_player` and experiment with `python3 -m pqcli`. It depends on your system but most likely no need to compile anything :)

**Comment by MelGrubb** [comment]
Let me see what I can do. I’ve never done any Python on my main machine, but 3.8 is present from other things I have installed.

**Comment by MelGrubb** [comment]
I’m not going to be very useful when it comes to Python, I’m afraid. Here’s what I see so far though

PS C:\Projects\pq-cli> python3.8 -m pqcli
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1729.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1729.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Projects\pq-cli\pqcli\__main__.py", line 6, in <module>
    import xdg
ModuleNotFoundError: No module named 'xdg'

This is running on Windows 10, by the way. I saw the other that someone had running on Windows. My actual installation is running on a Raspberry Pi, so I can try running this there and see if it does any better.

**Comment by MelGrubb** [comment]
Here’s what I got running this on a Raspberry Pi, which is the thing I want to auto-restart in the first place.

pi@raspberrypi:~/pq-cli $ python3 -m pqcli
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/pq-cli/pqcli/__main__.py", line 93, in <module>
    main()
  File "/home/pi/pq-cli/pqcli/__main__.py", line 85, in main
    ui = args.ui(roster, player, args)
UnboundLocalError: local variable 'player' referenced before assignment
pi@raspberrypi:~/pq-cli $

**Comment by rr-** [comment]
Looks like it's working :) There was a bug, which is now fixed.
Please see the new command line switch with --help.

**Comment by MelGrubb** [comment]
Excellent. That seems to have done it alright. I had installed it on the Pi originally through pip, figuring it would make updates easier in the future. I can run this cloned version for now until another official release is out. I used to have a character in the top 5% many many years ago. I figured a 24/7 Pi would be the best shot at getting back there. The CLI version doesn’t integrate with the leaderboard yet, does it? Is the leaderboard even still a thing? I’ll have to go look.

**Comment by MelGrubb** [comment]
I can’t believe I still had my old file. Check it out. Still ranked #2411 in Oobag: http://progressquest.com/search.php?name=penumbwraith
Now, I just need a way to continue his progress. Is there any way to load up .pq files? Could you tell me where they are? Even if it doesn’t update the leaderboard, it’s still progress in the hope that someday he’ll be able to upload.

From: Mel Grubb<mailto:melgrubb@live.com>
Sent: Wednesday, September 16, 2020 4:19 PM
To: rr-/pq-cli<mailto:reply@reply.github.com>
Subject: RE: [rr-/pq-cli] Feature request: Command-line parameters to specify which character to run (#15)

Excellent. That seems to have done it alright. I had installed it on the Pi originally through pip, figuring it would make updates easier in the future. I can run this cloned version for now until another official release is out. I used to have a character in the top 5% many many years ago. I figured a 24/7 Pi would be the best shot at getting back there. The CLI version doesn’t integrate with the leaderboard yet, does it? Is the leaderboard even still a thing? I’ll have to go look.

**Comment by rr-** [comment]
I'm sorry but pqcli is a completely separate project, so it does not support .pq files.

**Comment by MelGrubb** [comment]
Well that’s too bad. The Pi seems like the ideal platform for PQ. Well, this character can just run on his own then. Maybe I’ll pick up a used mini pc someday for Penumbwraith to live in.

**Comment by rr-** [comment]
Closing since the original issue has been solved :)

**Comment by MelGrubb** [comment]
It's funny. My character died of old age anyway a few months back. Timing.
