### ISSUE TITLE
XDG Dependency Renaming

### ISSUE THREAD

**Issue by noUsernamesLef7** [rr-/pq-cli#26]
Hello! It seems that the xdg dependency was [renamed xdg-base-dirs](https://github.com/srstevenson/xdg-base-dirs) last year as of version 6.0.0. This seems to present some packaging problems in distributions that have made this name change, such as Arch. pqcli now tries to import the pyxdg package and crashes with the message:

> module xdg has no attribute 'XDG_CONFIG_HOME'

I believe the fix for this is to bump the dependency version to at least 6.0.0, rename it to xdg-base-dirs, and change the import statement to xdg-base-dirs.

I'm not familiar with poetry at all, but if a pull request would be helpful, I can try to figure it out.

Thank you!

**Comment by nethershaw** [comment]
Implemented incorrectly.

https://github.com/rr-/pq-cli/commit/07cae1a4e8ef5e4404ae239a577d5330778fa0c0#r143757358
