### ISSUE TITLE
Run failed on missing _curses (Win10)

### ISSUE THREAD

**Issue by PetrGasparik** [rr-/pq-cli#5]
Hi,
I run pqcli from git source. After successfull build, I get "ModuleNotFoundError: No module named '_curses'"

What now? :) Thank you in advance!

Env: Win10, Python 3.7.1

**Comment by PetrGasparik** [comment]
`pip install windows-curses` did the trick, thou only --basic is supported
would be good to mention in README

trying to run pqcli --curses (or just default) leads to 
`Redirection is not supported.`

**Comment by rr-** [comment]
Thanks, soon I'll have an opportunity to test it on Windows. At very least windows-curses shouldn't be needed since --curses isn't working anyway. Thus let's leave this issue open.

**Comment by PetrGasparik** [comment]
I dont know why, but now curses work. Inbetween I just installed windows-curses and maybe closed and reopened cmd

**Comment by rr-** [comment]
So you just installed `pip3 install --user windows-curses`, is that right?
In that case I'll add it to the dependencies for the Windows platform in `setup.py`.

**Comment by PetrGasparik** [comment]
this: `pip install windows-curses`
plus I think cmd needs to be closed and open again

**Comment by rr-** [comment]
I've adjusted dependencies on master. Thanks for finding this.

**Comment by PetrGasparik** [comment]
it works, thans!
