### ISSUE TITLE
pqcli on Windows crashes on second save

### ISSUE THREAD

**Issue by PetrGasparik** [rr-/pq-cli#6]
When `pqcli --basic` reaches second save, it crashes on 
"FileExistsError: [WinError 183] Cannot create a file when that file already exists:: '$HOME\\.config\\pqcli\\save.dat' -> '$HOME\\.config\\pqcli\\save.dat.old'" 

According to https://stackoverflow.com/questions/54491021/why-am-i-getting-the-error-fileexistserror-winerror-183-cannot-create-a-file it can be solved by
`if not os.path.exists("name of folder"):`

**Comment by rr-** [comment]
@PetrGasparik could you paste a bit more of the stacktrace?

**Comment by PetrGasparik** [comment]
I solved this in PR #7 - look there if you agree :)

**Comment by rr-** [comment]
Done

**Comment by PetrGasparik** [comment]
thank you! it works now on win10
